import { FormEvent, useEffect, useMemo, useState } from "react";
import { api } from "./api";
import type { Project, Shift, Summary, Timesheet, User } from "./types";

type Tab = "record" | "monthly" | "calendar" | "team" | "about";
const today = new Date().toISOString().slice(0, 10);
const monthKey = today.slice(0, 7);
const labels: Record<string, string> = { submitted: "確認待ち", approved: "承認済み", rejected: "差し戻し", requested: "申請中" };
const tabLabel: Record<Tab, string> = { record: "作業を記録", monthly: "月次一覧", calendar: "カレンダー", team: "プロジェクト確認", about: "What is Workforce Hub" };

export default function App() {
  const [token, setToken] = useState(() => localStorage.getItem("workforce-token") ?? "");
  const [user, setUser] = useState<User | null>(() => { const value = localStorage.getItem("workforce-user"); return value ? JSON.parse(value) : null; });
  const [tab, setTab] = useState<Tab>("record");
  const [projects, setProjects] = useState<Project[]>([]);
  const [timesheets, setTimesheets] = useState<Timesheet[]>([]);
  const [shifts, setShifts] = useState<Shift[]>([]);
  const [summary, setSummary] = useState<Summary | null>(null);
  const [notice, setNotice] = useState("");
  const [month, setMonth] = useState(monthKey);
  const [payMode, setPayMode] = useState<"hourly" | "monthly">(() => localStorage.getItem("workforce-pay-mode") === "monthly" ? "monthly" : "hourly");
  const [hourlyRate, setHourlyRate] = useState(() => Number(localStorage.getItem("workforce-hourly-rate") ?? 1500));
  const [monthlySalary, setMonthlySalary] = useState(() => Number(localStorage.getItem("workforce-monthly-salary") ?? 240000));
  const manager = user?.role === "manager" || user?.role === "admin";
  const money = (hours: number) => new Intl.NumberFormat("ja-JP", { style: "currency", currency: "JPY", maximumFractionDigits: 0 }).format(hours * hourlyRate);
  const load = async () => {
    if (!token || !user) return;
    try {
      const [nextProjects, nextTimesheets, nextShifts, nextSummary] = await Promise.all([
        api<Project[]>("/api/projects", token), api<Timesheet[]>("/api/timesheets", token), api<Shift[]>("/api/shifts", token), manager ? api<Summary>("/api/dashboard/summary", token) : Promise.resolve(null),
      ]);
      setProjects(nextProjects); setTimesheets(nextTimesheets); setShifts(nextShifts); setSummary(nextSummary);
    } catch (error) { setNotice(error instanceof Error ? error.message : "データを取得できませんでした。"); }
  };
  useEffect(() => { void load(); }, [token, user?.role]);
  useEffect(() => { if (!notice) return; const timer = window.setTimeout(() => setNotice(""), 3600); return () => window.clearTimeout(timer); }, [notice]);
  const monthItems = useMemo(() => timesheets.filter((item) => item.workDate.startsWith(month)), [timesheets, month]);
  const monthHours = useMemo(() => monthItems.reduce((sum, item) => sum + Number(item.hours), 0), [monthItems]);
  const approvedHours = useMemo(() => monthItems.filter((item) => item.status === "approved").reduce((sum, item) => sum + Number(item.hours), 0), [monthItems]);
  const pendingCount = timesheets.filter((item) => item.status === "submitted").length + shifts.filter((item) => item.status === "requested").length;

  async function login(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); try { const result = await api<{ token: string; user: User }>("/api/auth/login", "", { method: "POST", body: JSON.stringify({ email: form.get("email"), password: form.get("password") }) }); localStorage.setItem("workforce-token", result.token); localStorage.setItem("workforce-user", JSON.stringify(result.user)); setToken(result.token); setUser(result.user); setNotice(""); } catch (error) { setNotice(error instanceof Error ? error.message : "ログインできませんでした。"); } }
  function logout() { localStorage.removeItem("workforce-token"); localStorage.removeItem("workforce-user"); setToken(""); setUser(null); }
  function saveRate(value: number) { const next = Math.max(0, value || 0); setHourlyRate(next); localStorage.setItem("workforce-hourly-rate", String(next)); }
  function saveSalary(value: number) { const next = Math.max(0, value || 0); setMonthlySalary(next); localStorage.setItem("workforce-monthly-salary", String(next)); }
  function changePayMode(value: "hourly" | "monthly") { setPayMode(value); localStorage.setItem("workforce-pay-mode", value); }
  async function addTimesheet(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); try { await api("/api/timesheets", token, { method: "POST", body: JSON.stringify({ projectId: Number(form.get("projectId")), workDate: form.get("workDate"), hours: Number(form.get("hours")), description: form.get("description") }) }); formElement.reset(); setNotice("作業記録を保存しました。確認が完了すると実績に反映されます。"); await load(); setTab("monthly"); } catch (error) { setNotice(error instanceof Error ? error.message : "保存できませんでした。"); } }
  async function approve(id: number, action: "approved" | "rejected") { try { await api(`/api/timesheets/${id}/approve`, token, { method: "PATCH", body: JSON.stringify({ action }) }); setNotice(action === "approved" ? "承認しました。" : "差し戻しました。"); await load(); } catch (error) { setNotice(error instanceof Error ? error.message : "更新できませんでした。"); } }
  async function addProject(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); try { await api("/api/projects", token, { method: "POST", body: JSON.stringify({ name: form.get("name"), clientName: form.get("clientName"), budgetHours: Number(form.get("budgetHours")), hourlyRate: form.get("hourlyRate") ? Number(form.get("hourlyRate")) : null }) }); formElement.reset(); await load(); setNotice("プロジェクトを追加しました。作業記録で選んで、最初の記録を追加しましょう。"); setTab("record"); } catch (error) { setNotice(error instanceof Error ? error.message : "プロジェクトを追加できませんでした。"); } }
  async function updateProject(project: Project, form: HTMLFormElement) { const values = new FormData(form); try { await api(`/api/projects/${project.id}`, token, { method: "PATCH", body: JSON.stringify({ name: values.get("name"), clientName: values.get("clientName"), budgetHours: Number(values.get("budgetHours")), hourlyRate: values.get("hourlyRate") ? Number(values.get("hourlyRate")) : null, status: values.get("status") }) }); setNotice("プロジェクトを更新しました。"); await load(); } catch (error) { setNotice(error instanceof Error ? error.message : "更新できませんでした。"); } }
  async function deleteProject(project: Project) { if (!window.confirm(`「${project.name}」を削除しますか？`)) return; try { await api(`/api/projects/${project.id}`, token, { method: "DELETE" }); setNotice("プロジェクトを削除しました。"); await load(); } catch (error) { setNotice(error instanceof Error ? error.message : "削除できませんでした。"); } }

  if (!user) return <main className="login-shell"><section className="login-card"><div className="brand-mark">WH</div><p className="eyebrow">WORKFORCE HUB</p><h1>働いた記録を、<br />分かりやすく。</h1><p className="muted">作業時間と収入見込みを、日々の記録からひと目で確認できるワークログアプリです。</p><form onSubmit={login}><label>メールアドレス<input name="email" type="email" defaultValue="manager@example.com" required /></label><label>パスワード<input name="password" type="password" defaultValue="demo1234" required /></label><button className="primary" type="submit">ログイン</button></form><div className="demo-note">管理者: manager@example.com / demo1234<br />メンバー: member@example.com / demo1234</div>{notice && <p className="notice error">{notice}</p>}</section></main>;

  const nav = (item: Tab) => <button key={item} onClick={() => setTab(item)} className={tab === item ? "nav active" : "nav"}>{tabLabel[item]}</button>;
  return <div className="app-shell"><aside><div className="logo"><span>WH</span>Workforce Hub</div><p className="workspace">MY WORK LOG</p>{nav("record")}{nav("monthly")}{nav("calendar")}{manager && nav("team")}{nav("about")}<div className="side-user"><b>{user.name}</b><small>{manager ? "マネージャー" : "メンバー"}</small><button onClick={logout}>ログアウト</button></div></aside><main className="content"><header><div><p className="eyebrow">{tab === "about" ? "ABOUT THIS APP" : "MY WORK LOG"}</p><h1>{tabLabel[tab]}</h1></div>{tab !== "about" && <div className="pending">要対応 <strong>{manager ? (summary?.pendingApprovals ?? pendingCount) : pendingCount}</strong>件</div>}</header>
    {tab === "record" && <Record projects={projects} onSubmit={addTimesheet} />}
    {tab === "monthly" && <Monthly items={monthItems} month={month} setMonth={setMonth} payMode={payMode} setPayMode={changePayMode} rate={hourlyRate} setRate={saveRate} salary={monthlySalary} setSalary={saveSalary} total={monthHours} approved={approvedHours} money={money} />}
    {tab === "calendar" && <Calendar month={month} setMonth={setMonth} items={monthItems} money={money} />}
    {tab === "team" && manager && <><ProjectForm onSubmit={addProject} /><ProjectManager projects={projects} onSave={updateProject} onDelete={deleteProject} /><Team items={timesheets} summary={summary} money={money} onApprove={approve} /></>}
    {tab === "about" && <About />}
  </main>{notice && <div className="toast" role="status"><span>✓</span>{notice}</div>}<nav className="mobile-nav">{nav("record")}{nav("monthly")}{nav("calendar")}{manager && nav("team")}{nav("about")}</nav></div>;
}

function Record({ projects, onSubmit }: { projects: Project[]; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) { return <div className="record-layout"><section className="record-intro"><p className="eyebrow">TODAY'S WORK</p><h2>今日やったことを<br />記録しましょう。</h2><p>日付・案件・作業時間・内容を入力するだけ。月の合計工数と収入見込みに自動で反映されます。</p><div className="tip">💡 作業時間は15分単位で入力できます。</div></section><section className="panel form-panel"><h2>作業を追加</h2><form onSubmit={onSubmit}><label>作業日<input name="workDate" type="date" defaultValue={today} required /></label><label>プロジェクト<select name="projectId" required>{projects.filter((p) => p.status === "active").map((p) => <option key={p.id} value={p.id}>{p.name} / {p.clientName}</option>)}</select></label><label>作業時間<input name="hours" type="number" min="0.25" max="24" step="0.25" placeholder="例: 3.25" required /></label><label>作業内容<textarea name="description" minLength={3} placeholder="例: 画面の仕様を確認し、修正内容をまとめた" required /></label><button className="primary">作業を記録する</button></form></section></div>; }

function Monthly({ items, month, setMonth, payMode, setPayMode, rate, setRate, salary, setSalary, total, approved, money }: { items: Timesheet[]; month: string; setMonth: (value: string) => void; payMode: "hourly" | "monthly"; setPayMode: (value: "hourly" | "monthly") => void; rate: number; setRate: (value: number) => void; salary: number; setSalary: (value: number) => void; total: number; approved: number; money: (hours: number) => string }) { const income = payMode === "hourly" ? money(total) : new Intl.NumberFormat("ja-JP", { style: "currency", currency: "JPY", maximumFractionDigits: 0 }).format(salary); return <><section className="monthly-controls"><label>表示する月<input aria-label="表示する月" type="month" value={month} onChange={(event) => setMonth(event.target.value)} /></label><label>収入の種類<select aria-label="収入の種類" value={payMode} onChange={(event) => setPayMode(event.target.value as "hourly" | "monthly")}><option value="hourly">時給</option><option value="monthly">月収（固定）</option></select></label>{payMode === "hourly" ? <label>時給設定<input aria-label="時給設定" type="number" min="0" step="100" value={rate} onChange={(event) => setRate(Number(event.target.value))} /><small>円 / 時間</small></label> : <label>月収設定<input aria-label="月収設定" type="number" min="0" step="1000" value={salary} onChange={(event) => setSalary(Number(event.target.value))} /><small>円 / 月</small></label>}</section><section className="metrics"><Metric label="今月の作業時間" value={`${total.toFixed(1)} h`} detail={`${items.length} 件の作業記録`} /><Metric label="収入見込み" value={income} detail={payMode === "hourly" ? `時給 ${money(1)} で試算` : "設定した固定月収"} /><Metric label="承認済み工数" value={`${approved.toFixed(1)} h`} detail="実績として確定した時間" /></section><section className="panel list-panel"><div className="panel-heading"><div><p className="eyebrow">MONTHLY WORK LOG</p><h2>{month.replace("-", "年")}月の作業一覧</h2></div><span className="total-pill">合計 {total.toFixed(1)} h</span></div><WorkTable items={items} money={money} /></section></>; }
function Metric({ label, value, detail }: { label: string; value: string; detail: string }) { return <article className="metric"><p>{label}</p><strong>{value}</strong><small>{detail}</small></article>; }
function WorkTable({ items, money }: { items: Timesheet[]; money: (hours: number) => string }) { if (!items.length) return <div className="empty">この月の作業記録はまだありません。</div>; return <div className="table-wrap"><table><thead><tr><th>日付</th><th>プロジェクト</th><th>作業内容</th><th>工数</th><th>見込み金額</th><th>状態</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td>{item.workDate}</td><td>{item.projectName}</td><td className="description">{item.description}</td><td><b>{item.hours} h</b></td><td>{money(Number(item.hours))}</td><td><span className={`status ${item.status}`}>{labels[item.status]}</span></td></tr>)}</tbody></table></div>; }
function ProjectForm({ onSubmit }: { onSubmit: (event: FormEvent<HTMLFormElement>) => void }) { return <section className="panel project-form"><div><p className="eyebrow">NEW PROJECT</p><h2>プロジェクトを追加</h2><p>追加後すぐに、作業記録の案件として選べます。</p></div><form onSubmit={onSubmit}><label>プロジェクト名<input name="name" placeholder="例: ECサイト改善" required /></label><label>取引先・部署<input name="clientName" placeholder="例: 株式会社サンプル" required /></label><label>予算時間<input name="budgetHours" type="number" min="1" step="1" placeholder="例: 80" required /></label><label>案件時給（任意）<input name="hourlyRate" type="number" min="0" step="100" placeholder="例: 1800" /></label><button className="primary">追加する</button></form></section> }
function ProjectManager({ projects, onSave, onDelete }: { projects: Project[]; onSave: (project: Project, form: HTMLFormElement) => void; onDelete: (project: Project) => void }) { return <section className="panel project-list"><div className="panel-heading"><div><p className="eyebrow">PROJECT SETTINGS</p><h2>登録済みプロジェクト</h2></div></div>{projects.map((project) => <form key={project.id} className="project-row" onSubmit={(event) => { event.preventDefault(); onSave(project, event.currentTarget); }}><input name="name" defaultValue={project.name} aria-label={`${project.name}の名前`} /><input name="clientName" defaultValue={project.clientName} aria-label={`${project.name}の取引先`} /><input name="budgetHours" type="number" min="1" defaultValue={project.budgetHours} aria-label={`${project.name}の予算時間`} /><input name="hourlyRate" type="number" min="0" defaultValue={project.hourlyRate ?? ""} placeholder="案件時給" aria-label={`${project.name}の案件時給`} /><select name="status" defaultValue={project.status} aria-label={`${project.name}の状態`}><option value="active">進行中</option><option value="paused">停止中</option><option value="completed">完了</option></select><button>保存</button><button type="button" className="delete-button" onClick={() => onDelete(project)}>削除</button></form>)}</section> }
function Calendar({ month, setMonth, items, money }: { month: string; setMonth: (value: string) => void; items: Timesheet[]; money: (hours: number) => string }) { const [year, monthNumber] = month.split("-").map(Number); const days = new Date(year, monthNumber, 0).getDate(); const first = new Date(year, monthNumber - 1, 1).getDay(); const byDay = new Map<number, Timesheet[]>(); const moveMonth = (offset: number) => { const date = new Date(year, monthNumber - 1 + offset, 1); setMonth(`${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}`); }; items.forEach((item) => { const day = Number(item.workDate.slice(8)); byDay.set(day, [...(byDay.get(day) ?? []), item]); }); return <><section className="monthly-controls calendar-controls"><button className="month-button" aria-label="前の月" onClick={() => moveMonth(-1)}>←</button><label>表示する月<input aria-label="カレンダーの月" type="month" value={month} onChange={(event) => setMonth(event.target.value)} /></label><button className="month-button" aria-label="次の月" onClick={() => moveMonth(1)}>→</button><p>日ごとの作業時間と収入見込みを確認できます。</p></section><section className="panel calendar-panel"><div className="weekdays">{"日 月 火 水 木 金 土".split(" ").map((d) => <span key={d}>{d}</span>)}</div><div className="calendar-grid">{Array.from({ length: first }, (_, index) => <div className="day blank" key={`blank-${index}`} />)}{Array.from({ length: days }, (_, index) => { const day = index + 1; const records = byDay.get(day) ?? []; const hours = records.reduce((sum, item) => sum + Number(item.hours), 0); return <article className={records.length ? "day has-work" : "day"} key={day}><b>{day}</b>{records.length > 0 && <><strong>{hours.toFixed(1)} h</strong><span>{money(hours)}</span><small>{records[0].projectName}{records.length > 1 ? ` ほか${records.length - 1}件` : ""}</small></>}</article>; })}</div></section></>; }
function Team({ items, summary, money, onApprove }: { items: Timesheet[]; summary: Summary | null; money: (hours: number) => string; onApprove: (id: number, action: "approved" | "rejected") => void }) { const waiting = items.filter((item) => item.status === "submitted"); return <><section className="metrics"><Metric label="承認待ち" value={`${waiting.length} 件`} detail="メンバーが提出した作業記録" /><Metric label="承認済み実績" value={`${(summary?.projectHours.reduce((sum, item) => sum + Number(item.actualHours), 0) ?? 0).toFixed(1)} h`} detail="全プロジェクトの合計" /><Metric label="承認済み金額" value={money(summary?.projectHours.reduce((sum, item) => sum + Number(item.actualHours), 0) ?? 0)} detail="設定した時給での参考値" /></section><section className="panel list-panel"><div className="panel-heading"><div><p className="eyebrow">WAITING FOR REVIEW</p><h2>確認が必要な作業記録</h2></div></div>{waiting.length ? <div className="table-wrap"><table><thead><tr><th>日付</th><th>メンバー</th><th>案件</th><th>内容</th><th>工数</th><th>操作</th></tr></thead><tbody>{waiting.map((item) => <tr key={item.id}><td>{item.workDate}</td><td>{item.memberName}</td><td>{item.projectName}</td><td className="description">{item.description}</td><td>{item.hours} h</td><td><div className="actions"><button onClick={() => onApprove(item.id, "approved")}>承認</button><button className="reject" onClick={() => onApprove(item.id, "rejected")}>差戻</button></div></td></tr>)}</tbody></table></div> : <div className="empty">今、確認が必要な作業記録はありません。</div>}</section></>; }
function About() { return <><section className="overview-hero"><p className="eyebrow">WHAT IS WORKFORCE HUB?</p><h2>働いた記録を、<br />見える化するためのアプリ。</h2><p>日々の作業を記録すると、月ごとの工数と収入見込みを自動で集計。メンバーは自分の働き方を振り返れ、管理者はチームの実績を確認できます。</p></section><section className="overview-grid"><article className="panel"><p className="eyebrow">FOR WORKERS</p><h2>自分の作業を整理</h2><ul><li>案件ごとの作業時間を記録</li><li>月の合計工数と収入見込みを確認</li><li>カレンダーで日々の働き方を振り返る</li></ul></article><article className="panel"><p className="eyebrow">FOR MANAGERS</p><h2>チームの記録を確認</h2><ul><li>メンバーの提出を承認・差し戻し</li><li>プロジェクト別の実績を確認</li><li>案件ごとの稼働を把握</li></ul></article></section><section className="panel flow-panel"><p className="eyebrow">WORKFLOW</p><h2>使い方はシンプル</h2><div className="flow"><div><b>1</b><strong>記録</strong><span>作業した時間と内容を入力</span></div><i>→</i><div><b>2</b><strong>集計</strong><span>月の工数と金額を自動計算</span></div><i>→</i><div><b>3</b><strong>振り返り</strong><span>カレンダーで働き方を確認</span></div><i>→</i><div><b>4</b><strong>承認</strong><span>管理者が実績を確認</span></div></div></section></>; }
